slam_toolbox:
  ros__parameters:
    use_sim_time: True
    map_frame: map
    base_frame: base_link
    odom_frame: odom
    scan_topic: /scan
    mode: mapping
    resolution: 0.05
    max_laser_range: 10.0
    minimum_time_interval: 0.5
    use_scan_matching: true
    publish_map_period: 1.0
